import { ChartFrame } from "../../shared/ChartFrame";
import { DataStateLabel, FactualCandidateNotice } from "../../shared/Semantic";
import { RankedList } from "../../shared/RankedList";
import { findSelectedNode } from "../../state/routeSchema";
import type { NavigationNode } from "../../data/publicSnapshotTypes";
import type { ViewProps } from "../viewProps";

function displayObservation(value: string, unit: string) {
  if (unit === "million_barrels") return `${value} million barrels`;
  if (unit === "percent") return `${value}%`;
  if (unit === "thousands") return `${Number(value).toLocaleString("en-US", { minimumFractionDigits: 1 })} thousand`;
  return `${value} ${unit.replaceAll("_", " ")}`;
}

export default function SummaryView({ snapshot, phase4b, route, navigate, variant }: ViewProps) {
  const selected = findSelectedNode(snapshot, route);
  const metrics = snapshot.extensions["auxsays.phase2.metrics"];
  if (snapshot.snapshot.publicationClass === "factual") {
    if (phase4b) {
      const relationshipCount = phase4b.acceptedRelationships.length;
      const calculationCount = phase4b.structuralCalculations.length;
      return <div className="sm-view sm-view--summary sm-view--structural-checkpoint">
        <header className="sm-view-header"><div><span className="sm-eyebrow">Summary / Local factual checkpoint</span><h1 data-route-heading tabIndex={-1}>Energy-to-transport system state</h1><p className="sm-view-deck">Official observations are available. Structural relationships are still pending acceptance.</p></div><div className="sm-current-state"><DataStateLabel state="OBS" /><strong>{phase4b.observations.length} factual observations</strong><span>Gate B open</span></div></header>
        <section className="sm-state-counts" aria-label="Observation and calculation identity"><article><DataStateLabel state="OBS" /><strong>{phase4b.observations.length}</strong><span>Official measurements</span></article><article><DataStateLabel state="CALC" /><strong>{calculationCount}</strong><span>AUXSAYS structural calculations</span></article><article><span className="sm-status-dot sm-status-dot--pending" aria-hidden="true" /><strong>{relationshipCount}</strong><span>Accepted structural relationships</span></article></section>
        <section className="sm-observation-strip" aria-labelledby="current-observations"><div className="sm-section-heading"><div><span className="sm-eyebrow">Known now</span><h2 id="current-observations">Current official observations</h2></div><small>OBS means published measurement, not an AUXSAYS calculation.</small></div><div>{phase4b.observations.map((observation) => <article key={observation.id}><DataStateLabel state="OBS" /><strong>{displayObservation(observation.value, observation.unit)}</strong><h3>{observation.label}</h3><span>{observation.period}</span></article>)}</div></section>
        <section className="sm-structural-home" aria-labelledby="structural-model-title"><div className="sm-structural-home__heading"><div><span className="sm-eyebrow">Structural model</span><h2 id="structural-model-title">Awaiting authoritative BEA acceptance</h2><p>There are no accepted factual paths to draw yet.</p></div><span className="sm-gate-badge">Gate B open</span></div><div className="sm-structural-stage" aria-label="Structural proof progress"><article><span>01</span><strong>Official inputs</strong><b>{phase4b.observations.length} OBS</b></article><article className="is-pending"><span>02</span><strong>Accepted paths</strong><b>{relationshipCount}</b></article><article className="is-pending"><span>03</span><strong>Structural result</strong><b>{calculationCount} CALC</b></article></div><div className="sm-blocked-state"><span className="sm-status-dot sm-status-dot--pending" aria-hidden="true" /><div><strong>Structural relationships pending</strong><p>Official BEA structural data has not yet been accepted.</p></div><details><summary>Technical status</summary><dl><div><dt>Source state</dt><dd><code>{phase4b.sourceHealth.beaInputOutput}</code></dd></div><div><dt>Coverage</dt><dd>{phase4b.coverageWarning}</dd></div><div><dt>In-scope codes</dt><dd>{phase4b.coveredCodes.join(", ")}</dd></div><div><dt>Human check</dt><dd>{phase4b.humanPhase4bQa}</dd></div></dl></details></div></section>
      </div>;
    }
    const primary = metrics[0];
    return <div className="sm-view sm-view--summary"><header className="sm-view-header"><div><span className="sm-eyebrow">Summary / Local factual mode</span><h1 data-route-heading tabIndex={-1}>U.S. labor observations</h1></div><div className="sm-current-state"><DataStateLabel state="OBS" /><strong>Factual candidate</strong><span>As known {snapshot.snapshot.asOf}</span></div></header><FactualCandidateNotice compact /><div className="sm-primary-layout"><ChartFrame title={primary.label} description="Latest rights-cleared factual observation in the local Phase-3 review candidate." stateType="OBS" data={primary.series} unit={primary.unit} publicationClass="factual" /><aside className="sm-kpis" aria-label="Factual labor observations">{metrics.slice(0, 4).map((metric) => <article key={metric.id}><DataStateLabel state="OBS" /><strong>{metric.displayValue}</strong><span>{metric.label} · {metric.validTime}</span></article>)}</aside></div><section className="sm-evidence-table" aria-labelledby="factual-observations"><div className="sm-section-heading"><div><span className="sm-eyebrow">Rights-cleared OBS only</span><h2 id="factual-observations">Six-indicator first slice</h2></div></div><div className="sm-table-scroll" role="region" aria-label="Factual labor observations" tabIndex={0}><table><thead><tr><th>Indicator</th><th>Value</th><th>Observation period</th><th>Source</th></tr></thead><tbody>{metrics.map((metric) => <tr key={metric.id}><th scope="row">{metric.label}</th><td>{metric.displayValue}</td><td>{metric.validTime}</td><td>{metric.sourceRefs.join(", ")}</td></tr>)}</tbody></table></div></section></div>;
  }
  const primary = metrics[0];
  const children = selected.children ?? [];
  const demand = snapshot.outlook.demandAllocation[0];
  return <div className="sm-view sm-view--summary"><header className="sm-view-header"><div><span className="sm-eyebrow">Summary / Current state</span><h1 data-route-heading tabIndex={-1}>{selected.label}</h1></div><div className="sm-current-state"><DataStateLabel state="OBS" /><strong>Current fixture</strong><span>As of {snapshot.snapshot.asOf}</span></div></header><div className="sm-primary-layout"><ChartFrame title="Synthetic state trajectory" description="Observed fixture series in synthetic-index-points; not an economic finding." stateType={primary.stateType} data={primary.series} unit={primary.unit} /><aside className="sm-kpis" aria-label="Synthetic state indicators"><article><DataStateLabel state="OBS" /><strong>{metrics[0].displayValue}</strong><span>Observed signal</span></article><article><DataStateLabel state="CALC" /><strong>{metrics[1].displayValue}</strong><span>Calculated state</span></article><article><DataStateLabel state="FCST" /><strong>{snapshot.outlook.forecasts[0].displayRange}</strong><span>Outlook range</span></article><article><DataStateLabel state="SCEN" /><strong>Conditional</strong><span>Scenario</span></article></aside></div>{children.length > 0 ? <RankedList title={`${selected.label.replace("SYNTHETIC TEST ", "")} ranked drivers`} items={children} onSelect={(item) => navigate((current) => ({ ...current, path: [...current.path, (item as NavigationNode).slug] }))} selectionLabel="Drill in" /> : <section className="sm-empty-context"><h2>Leaf factor reached</h2><p>Use the breadcrumb to move up.</p></section>}<div className="sm-support-grid"><section><span className="sm-eyebrow">Mover / event</span><h2>{snapshot.events[0].label.replace("SYNTHETIC TEST ", "")}</h2><p><DataStateLabel state={snapshot.events[0].stateType} /> Linked to test provenance.</p></section><section><span className="sm-eyebrow">Demand preview</span><h2>{demand.label.replace("SYNTHETIC TEST ", "")}</h2><p><strong>{demand.allocationType}</strong> · {demand.displayValue}</p><small>{demand.changeLabel}</small></section><section><span className="sm-eyebrow">Hiring preview</span><h2>{snapshot.outlook.occupations[0].label.replace("SYNTHETIC TEST ", "")}</h2><p>{snapshot.outlook.occupations[0].displayValue}</p><small>Expected openings</small></section></div>{variant === "partial-payload" && <section className="sm-state-panel"><h2>Supporting source module unavailable</h2><p>The primary validated fixture remains visible; missing evidence is not replaced.</p></section>}</div>;
}
