import { ChartFrame } from "../../shared/ChartFrame";
import { DataStateLabel } from "../../shared/Semantic";
import { RankedList } from "../../shared/RankedList";
import { findSelectedNode } from "../../state/routeSchema";
import type { NavigationNode } from "../../data/publicSnapshotTypes";
import type { ViewProps } from "../viewProps";

export default function SummaryView({ snapshot, route, navigate, variant }: ViewProps) {
  const selected = findSelectedNode(snapshot, route);
  const metrics = snapshot.extensions["auxsays.phase2.metrics"];
  const primary = metrics[0];
  const children = selected.children ?? [];
  const demand = snapshot.outlook.demandAllocation[0];
  return <div className="sm-view sm-view--summary"><header className="sm-view-header"><div><span className="sm-eyebrow">Summary / Current state</span><h1 data-route-heading tabIndex={-1}>{selected.label}</h1></div><div className="sm-current-state"><DataStateLabel state="OBS" /><strong>Current fixture</strong><span>As of {snapshot.snapshot.asOf}</span></div></header><div className="sm-primary-layout"><ChartFrame title="Synthetic state trajectory" description="Observed fixture series in synthetic-index-points; not an economic finding." stateType={primary.stateType} data={primary.series} unit={primary.unit} /><aside className="sm-kpis" aria-label="Synthetic state indicators"><article><DataStateLabel state="OBS" /><strong>{metrics[0].displayValue}</strong><span>Observed signal</span></article><article><DataStateLabel state="CALC" /><strong>{metrics[1].displayValue}</strong><span>Calculated state</span></article><article><DataStateLabel state="FCST" /><strong>{snapshot.outlook.forecasts[0].displayRange}</strong><span>Outlook range</span></article><article><DataStateLabel state="SCEN" /><strong>Conditional</strong><span>Scenario</span></article></aside></div>{children.length > 0 ? <RankedList title={`${selected.label.replace("SYNTHETIC TEST ", "")} ranked drivers`} items={children} onSelect={(item) => navigate((current) => ({ ...current, path: [...current.path, (item as NavigationNode).slug] }))} selectionLabel="Drill in" /> : <section className="sm-empty-context"><h2>Leaf factor reached</h2><p>Use the breadcrumb to move up.</p></section>}<div className="sm-support-grid"><section><span className="sm-eyebrow">Mover / event</span><h2>{snapshot.events[0].label.replace("SYNTHETIC TEST ", "")}</h2><p><DataStateLabel state={snapshot.events[0].stateType} /> Linked to test provenance.</p></section><section><span className="sm-eyebrow">Demand preview</span><h2>{demand.label.replace("SYNTHETIC TEST ", "")}</h2><p><strong>{demand.allocationType}</strong> · {demand.displayValue}</p><small>{demand.changeLabel}</small></section><section><span className="sm-eyebrow">Hiring preview</span><h2>{snapshot.outlook.occupations[0].label.replace("SYNTHETIC TEST ", "")}</h2><p>{snapshot.outlook.occupations[0].displayValue}</p><small>Expected openings</small></section></div>{variant === "partial-payload" && <section className="sm-state-panel"><h2>Supporting source module unavailable</h2><p>The primary validated fixture remains visible; missing evidence is not replaced.</p></section>}</div>;
}
