import { useState } from "react";
import { ChartFrame } from "../../shared/ChartFrame";
import { DataStateLabel, FactualCandidateNotice, SourceEvidenceLink } from "../../shared/Semantic";
import { SystemIcon, type SystemIconName } from "../../shared/SystemIcon";
import { RankedList } from "../../shared/RankedList";
import { findSelectedNode } from "../../state/routeSchema";
import type { NavigationNode } from "../../data/publicSnapshotTypes";
import type { ViewProps } from "../viewProps";

function displayObservation(value: string, unit: string) {
  if (unit === "million_barrels") return `${value} million barrels`;
  if (unit === "percent") return `${value}%`;
  if (unit === "thousands") return `${Number(value).toLocaleString("en-US", { minimumFractionDigits: 1 })} thousand`;
  return `${value} ${unit.replaceAll("_", " ")}`;
}

export default function SummaryView({ snapshot, phase4b, route, navigate, variant }: ViewProps) {
  const [selectedSignal, setSelectedSignal] = useState(0);
  const selected = findSelectedNode(snapshot, route);
  const metrics = snapshot.extensions["auxsays.phase2.metrics"];
  if (snapshot.snapshot.publicationClass === "factual") {
    if (phase4b) {
      const relationshipCount = phase4b.acceptedRelationships.length;
      const calculationCount = phase4b.structuralCalculations.length;
      const signal = phase4b.observations[selectedSignal];
      const icons: SystemIconName[] = ["barrel", "gauge", "truck"];
      return <div className="sm-view sm-view--summary sm-view--signal-experience">
        <header className="sm-hero"><div><span className="sm-kicker"><i aria-hidden="true" />Live U.S. signals</span><h1 data-route-heading tabIndex={-1}>Energy pressure.<br /><em>Made legible.</em></h1><p>Three official measurements. One emerging system view. Nothing invented.</p></div><div className="sm-hero-orbit" aria-hidden="true"><SystemIcon name="network" size={46} /><span /><span /><span /></div></header>

        <section className="sm-signal-deck" aria-labelledby="signal-deck-title"><div className="sm-section-intro"><div><span>01</span><div><small>What we know</small><h2 id="signal-deck-title">Current signals</h2></div></div><p>Choose a signal to peel back its evidence.</p></div><div className="sm-signal-grid">{phase4b.observations.map((observation, index) => <button type="button" key={observation.id} className={selectedSignal === index ? "is-selected" : ""} aria-pressed={selectedSignal === index} onClick={() => setSelectedSignal(index)}><span className="sm-signal-icon"><SystemIcon name={icons[index] ?? "database"} size={28} /></span><strong>{displayObservation(observation.value, observation.unit)}</strong><span>{observation.label}</span><small>{observation.period}</small></button>)}</div>
          <article className="sm-signal-focus" aria-live="polite"><div className="sm-signal-focus__visual"><span><SystemIcon name={icons[selectedSignal] ?? "database"} size={38} /></span><i aria-hidden="true" /></div><div><small>Official measurement</small><h3>{signal.label}</h3><strong>{displayObservation(signal.value, signal.unit)}</strong><p>{signal.authority} · {signal.period}</p></div><div className="sm-signal-actions"><SourceEvidenceLink href={signal.evidenceUrl}>Open source <SystemIcon name="arrow" size={17} /></SourceEvidenceLink><button type="button" onClick={() => navigate((current) => ({ ...current, view: "verified" }))}>Peel back details</button></div></article>
        </section>

        <section className="sm-model-reveal" aria-labelledby="model-reveal-title"><div className="sm-section-intro"><div><span>02</span><div><small>What comes next</small><h2 id="model-reveal-title">The structural model</h2></div></div><span className="sm-model-state">Gate B open</span></div><div className="sm-model-canvas"><div className="sm-model-inputs"><span><SystemIcon name="database" size={25} /></span><strong>{phase4b.observations.length} signals ready</strong><small>Official inputs captured</small></div><div className="sm-model-lock"><span><SystemIcon name="lock" size={34} /></span><strong>Connections pending</strong><p>Official BEA structure has not been accepted yet, so no arrows are drawn.</p></div><div className="sm-model-output"><span><SystemIcon name="network" size={25} /></span><strong>No system result yet</strong><small>{calculationCount} calculations · {relationshipCount} accepted paths</small></div></div><details className="sm-technical-drawer"><summary>Why is the model waiting? <span>View technical state</span></summary><div><p>{phase4b.coverageWarning}</p><dl><div><dt>BEA source</dt><dd>{phase4b.sourceHealth.beaInputOutput}</dd></div><div><dt>In-scope codes</dt><dd>{phase4b.coveredCodes.join(", ")}</dd></div><div><dt>Human review</dt><dd>{phase4b.humanPhase4bQa}</dd></div></dl></div></details></section>

        <section className="sm-truth-rail" aria-label="Claim identity"><div><SystemIcon name="check" size={18} /><span><strong>Measured</strong> by official sources</span></div><div><SystemIcon name="lock" size={18} /><span><strong>Calculated</strong> nothing structural yet</span></div><div><SystemIcon name="arrow" size={18} /><span><strong>Forecasting</strong> begins after Gate B</span></div></section>
      </div>;
    }
    const primary = metrics[0];
    return <div className="sm-view sm-view--summary"><header className="sm-view-header"><div><span className="sm-eyebrow">Summary / Local factual mode</span><h1 data-route-heading tabIndex={-1}>U.S. labor observations</h1></div><div className="sm-current-state"><DataStateLabel state="OBS" /><strong>Factual candidate</strong><span>As known {snapshot.snapshot.asOf}</span></div></header><FactualCandidateNotice compact /><div className="sm-primary-layout"><ChartFrame title={primary.label} description="Latest rights-cleared factual observation in the local Phase-3 review candidate." stateType="OBS" data={primary.series} unit={primary.unit} publicationClass="factual" /><aside className="sm-kpis" aria-label="Factual labor observations">{metrics.slice(0, 4).map((metric) => <article key={metric.id}><DataStateLabel state="OBS" /><strong>{metric.displayValue}</strong><span>{metric.label} · {metric.validTime}</span></article>)}</aside></div><section className="sm-evidence-table" aria-labelledby="factual-observations"><div className="sm-section-heading"><div><span className="sm-eyebrow">Rights-cleared OBS only</span><h2 id="factual-observations">Six-indicator first slice</h2></div></div><div className="sm-table-scroll" role="region" aria-label="Factual labor observations" tabIndex={0}><table><thead><tr><th>Indicator</th><th>Value</th><th>Observation period</th><th>Source</th></tr></thead><tbody>{metrics.map((metric) => <tr key={metric.id}><th scope="row">{metric.label}</th><td>{metric.displayValue}</td><td>{metric.validTime}</td><td>{metric.sourceRefs.join(", ")}</td></tr>)}</tbody></table></div></section></div>;
  }
  const primary = metrics[0];
  const children = selected.children ?? [];
  const demand = snapshot.outlook.demandAllocation[0];
  return <div className="sm-view sm-view--summary"><header className="sm-view-header"><div><span className="sm-eyebrow">Summary / Current state</span><h1 data-route-heading tabIndex={-1}>{selected.label}</h1></div><div className="sm-current-state"><DataStateLabel state="OBS" /><strong>Current fixture</strong><span>As of {snapshot.snapshot.asOf}</span></div></header><div className="sm-primary-layout"><ChartFrame title="Synthetic state trajectory" description="Observed fixture series in synthetic-index-points; not an economic finding." stateType={primary.stateType} data={primary.series} unit={primary.unit} /><aside className="sm-kpis" aria-label="Synthetic state indicators"><article><DataStateLabel state="OBS" /><strong>{metrics[0].displayValue}</strong><span>Observed signal</span></article><article><DataStateLabel state="CALC" /><strong>{metrics[1].displayValue}</strong><span>Calculated state</span></article><article><DataStateLabel state="FCST" /><strong>{snapshot.outlook.forecasts[0].displayRange}</strong><span>Outlook range</span></article><article><DataStateLabel state="SCEN" /><strong>Conditional</strong><span>Scenario</span></article></aside></div>{children.length > 0 ? <RankedList title={`${selected.label.replace("SYNTHETIC TEST ", "")} ranked drivers`} items={children} onSelect={(item) => navigate((current) => ({ ...current, path: [...current.path, (item as NavigationNode).slug] }))} selectionLabel="Drill in" /> : <section className="sm-empty-context"><h2>Leaf factor reached</h2><p>Use the breadcrumb to move up.</p></section>}<div className="sm-support-grid"><section><span className="sm-eyebrow">Mover / event</span><h2>{snapshot.events[0].label.replace("SYNTHETIC TEST ", "")}</h2><p><DataStateLabel state={snapshot.events[0].stateType} /> Linked to test provenance.</p></section><section><span className="sm-eyebrow">Demand preview</span><h2>{demand.label.replace("SYNTHETIC TEST ", "")}</h2><p><strong>{demand.allocationType}</strong> · {demand.displayValue}</p><small>{demand.changeLabel}</small></section><section><span className="sm-eyebrow">Hiring preview</span><h2>{snapshot.outlook.occupations[0].label.replace("SYNTHETIC TEST ", "")}</h2><p>{snapshot.outlook.occupations[0].displayValue}</p><small>Expected openings</small></section></div>{variant === "partial-payload" && <section className="sm-state-panel"><h2>Supporting source module unavailable</h2><p>The primary validated fixture remains visible; missing evidence is not replaced.</p></section>}</div>;
}
