import { useId, useMemo, useState } from "react";
import type { TraceModel } from "../../data/publicSnapshotTypes";
import { DataStateLabel } from "../../shared/Semantic";

const positions = [
  [60, 90], [230, 90], [400, 90], [570, 90], [400, 210], [230, 210]
] as const;

export default function TraceMode({ trace, onClose }: { trace: TraceModel; onClose: () => void }) {
  const titleId = useId();
  const [selected, setSelected] = useState(trace.nodes[0].id);
  const connectedEdges = useMemo(() => new Set(trace.edges.filter((edge) => edge.from === selected || edge.to === selected).map((edge) => edge.id)), [trace, selected]);
  const connectedNodes = useMemo(() => new Set([selected, ...trace.edges.filter((edge) => edge.from === selected || edge.to === selected).flatMap((edge) => [edge.from, edge.to])]), [trace, selected]);
  const point = Object.fromEntries(trace.nodes.map((node, index) => [node.id, positions[index]]));
  return <section className="sm-trace" aria-labelledby={titleId}><div className="sm-section-heading"><div><span className="sm-eyebrow">Bounded Trace / Explanation</span><h2 id={titleId}>Synthetic relationship path</h2></div><button type="button" onClick={onClose}>Return to Outlook</button></div><details className="sm-inspector-details"><summary>How selection is encoded</summary><p>Motion and line prominence show selection only. They do not encode probability, evidence strength, or causal certainty.</p></details><div className="sm-trace-canvas"><svg viewBox="0 0 640 290" role="img" aria-label="Visual map of the bounded synthetic trace; use the node controls and relationship table for complete accessible detail."><defs><marker id="sm-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" /></marker></defs>{trace.edges.map((edge) => { const from = point[edge.from]; const to = point[edge.to]; return <line key={edge.id} x1={from[0]} y1={from[1]} x2={to[0]} y2={to[1]} className={connectedEdges.has(edge.id) ? `is-active is-${edge.direction}` : "is-dimmed"} markerEnd="url(#sm-arrow)" />; })}{trace.nodes.map((node, index) => <g key={node.id} className={connectedNodes.has(node.id) ? "is-active" : "is-dimmed"}><circle cx={positions[index][0]} cy={positions[index][1]} r="28" /><text x={positions[index][0]} y={positions[index][1] + 4} textAnchor="middle">{index + 1}</text></g>)}</svg><div className="sm-trace-node-controls" aria-label="Trace node controls">{trace.nodes.map((node, index) => <button type="button" key={node.id} aria-pressed={selected === node.id} onClick={() => setSelected(node.id)}><span>{index + 1}</span><strong>{node.label.replace("SYNTHETIC TEST ", "")}</strong><DataStateLabel state={node.stateType} /></button>)}</div></div><div className="sm-table-scroll" role="region" aria-label="Trace relationship list" tabIndex={0}><table><caption>Complete synthetic relationship list</caption><thead><tr><th>Relationship</th><th>Class</th><th>Direction</th><th>Lag</th><th>Evidence</th><th>Provenance</th></tr></thead><tbody>{trace.edges.map((edge) => <tr key={edge.id} className={connectedEdges.has(edge.id) ? "is-selected" : ""}><th scope="row">{trace.nodes.find((node) => node.id === edge.from)?.label.replace("SYNTHETIC TEST ", "")} → {trace.nodes.find((node) => node.id === edge.to)?.label.replace("SYNTHETIC TEST ", "")}<small>{edge.description}</small></th><td><span className={`sm-relationship sm-relationship--${edge.classification.toLowerCase()}`}>{edge.classification}</span></td><td>{edge.direction}</td><td>{edge.lag}</td><td>{edge.evidenceStrength}</td><td>{edge.provenanceRef}</td></tr>)}</tbody></table></div></section>;
}
