import { ChartFrame } from "../../shared/ChartFrame";
import { DataStateLabel, FixtureNotice, FreshnessLabel, SourceEvidenceLink } from "../../shared/Semantic";
import type { SourceRecord } from "../../data/publicSnapshotTypes";
import type { ViewProps } from "../viewProps";

function SourceInspectorContent({ sources }: { sources: SourceRecord[] }) {
  return <><span className="sm-eyebrow">Source inspector</span><h2>Timing and provenance</h2>{sources.map((source) => <article key={source.sourceId}><div><strong>{source.provider}</strong><FreshnessLabel state={source.freshness} /></div><dl><div><dt>Dataset</dt><dd>{source.dataset}</dd></div><div><dt>Observation</dt><dd>{source.observationTime}</dd></div><div><dt>Source publication</dt><dd>{source.publishedAt}</dd></div><div><dt>Retrieved</dt><dd>{source.retrievedAt}</dd></div><div><dt>Freshness evaluated</dt><dd>{source.freshnessEvaluatedAt}</dd></div><div><dt>Next expected release</dt><dd>{source.nextExpectedReleaseAt}</dd></div><div><dt>Revision / vintage</dt><dd>{source.revision} / {source.vintage}</dd></div><div><dt>Why this state</dt><dd>{source.freshnessReason}</dd></div></dl><SourceEvidenceLink href={source.methodologyUrl}>Open fixture methodology boundary</SourceEvidenceLink></article>)}</>;
}

export default function VerifiedDataView({ snapshot, route, navigate }: ViewProps) {
  const metrics = snapshot.extensions["auxsays.phase2.metrics"];
  const sources = Object.values(snapshot.sources);
  const geographies = snapshot.extensions["auxsays.phase2.geographies"];
  const ranges = snapshot.extensions["auxsays.phase2.ranges"];
  return <div className="sm-view sm-view--verified"><header className="sm-view-header"><div><span className="sm-eyebrow">Verified Data / Evidence first</span><h1 data-route-heading tabIndex={-1}>Observed and calculated fixture evidence</h1><p>Source timing, vintage, method, and cadence-relative freshness remain separate.</p></div><div className="sm-control-pair"><label>Geography<select value={route.geo} onChange={(event) => navigate((current) => ({ ...current, geo: event.target.value }))}>{geographies.map((geo) => <option key={geo.id} value={geo.id}>{geo.label}</option>)}</select></label><label>Range<select value={route.range} onChange={(event) => navigate((current) => ({ ...current, range: event.target.value }))}>{ranges.map((range) => <option key={range.id} value={range.id}>{range.label}</option>)}</select></label></div></header><div className="sm-primary-layout"><ChartFrame title="Verified fixture history" description="OBS and CALC are shown as separate series in the evidence view. The chart has point controls and a complete table alternative." stateType="OBS" data={metrics[0].series} unit={metrics[0].unit} /><aside className="sm-inspector sm-inspector--desktop" aria-label="Source inspector"><SourceInspectorContent sources={sources} /></aside><details className="sm-inspector sm-inspector--mobile"><summary>Source inspector <span>Open / close evidence sheet</span></summary><SourceInspectorContent sources={sources} /></details></div><section className="sm-evidence-table" aria-labelledby="raw-fixture-title"><div className="sm-section-heading"><div><span className="sm-eyebrow">Read-only public view model</span><h2 id="raw-fixture-title">Typed fixture records</h2></div><FixtureNotice compact /></div><div className="sm-table-scroll" role="region" aria-label="Typed fixture records" tabIndex={0}><table><thead><tr><th>Record</th><th>State</th><th>Value</th><th>Valid time</th><th>Method / provenance</th></tr></thead><tbody>{metrics.map((metric) => <tr key={metric.id}><th scope="row">{metric.label}</th><td><DataStateLabel state={metric.stateType} /></td><td>{metric.displayValue}</td><td>{metric.validTime}</td><td>{metric.method ?? metric.provenanceRefs.join(", ")}</td></tr>)}</tbody></table></div></section><section className="sm-timing-strip"><h2>Snapshot timing is not source timing</h2><dl><div><dt>System evaluated</dt><dd>{snapshot.snapshot.evaluatedAt}</dd></div><div><dt>Snapshot generated</dt><dd>{snapshot.snapshot.generatedAt}</dd></div><div><dt>Snapshot published</dt><dd>{snapshot.snapshot.publishedAt}</dd></div><div><dt>Knowledge cutoff</dt><dd>{snapshot.snapshot.asOf}</dd></div></dl></section></div>;
}
