import { ChartFrame } from "../../shared/ChartFrame";
import { DataStateLabel, FactualCandidateNotice, FixtureNotice, FreshnessLabel, SourceEvidenceLink } from "../../shared/Semantic";
import type { SourceRecord } from "../../data/publicSnapshotTypes";
import type { ViewProps } from "../viewProps";

function SourceInspectorContent({ sources, factual }: { sources: SourceRecord[]; factual: boolean }) {
  return <><span className="sm-eyebrow">Source inspector</span><h2>Timing and provenance</h2>{sources.map((source) => <article key={source.sourceId}><div><strong>{source.provider}</strong><FreshnessLabel state={source.freshness} /></div><dl><div><dt>Dataset</dt><dd>{source.dataset}</dd></div><div><dt>Observation</dt><dd>{source.observationTime}</dd></div><div><dt>Source publication</dt><dd>{source.publishedAt}</dd></div><div><dt>Retrieved</dt><dd>{source.retrievedAt}</dd></div><div><dt>Freshness evaluated</dt><dd>{source.freshnessEvaluatedAt}</dd></div><div><dt>Next expected release</dt><dd>{source.nextExpectedReleaseAt}</dd></div><div><dt>Revision / vintage</dt><dd>{source.revision} / {source.vintage}</dd></div><div><dt>Why this state</dt><dd>{source.freshnessReason}</dd></div></dl><SourceEvidenceLink href={source.methodologyUrl}>{factual ? "Open official methodology" : "Open fixture methodology boundary"}</SourceEvidenceLink></article>)}</>;
}

export default function VerifiedDataView({ snapshot, route, navigate }: ViewProps) {
  const metrics = snapshot.extensions["auxsays.phase2.metrics"];
  const sources = Object.values(snapshot.sources);
  const geographies = snapshot.extensions["auxsays.phase2.geographies"];
  const ranges = snapshot.extensions["auxsays.phase2.ranges"];
  const factual = snapshot.snapshot.publicationClass === "factual";
  return <div className="sm-view sm-view--verified"><header className="sm-view-header"><div><span className="sm-eyebrow">Verified Data / Evidence</span><h1 data-route-heading tabIndex={-1}>{factual ? "Observed factual evidence — local review candidate" : "Observed and calculated fixture evidence"}</h1></div><div className="sm-control-pair"><label>Geography<select value={route.geo} onChange={(event) => navigate((current) => ({ ...current, geo: event.target.value }))}>{geographies.map((geo) => <option key={geo.id} value={geo.id}>{geo.label}</option>)}</select></label><label>Range<select value={route.range} onChange={(event) => navigate((current) => ({ ...current, range: event.target.value }))}>{ranges.map((range) => <option key={range.id} value={range.id}>{range.label}</option>)}</select></label></div></header><div className="sm-primary-layout"><ChartFrame title={factual ? metrics[0].label : "Verified fixture history"} description={factual ? "Latest factual observation with separate valid, public, retrieved, and accepted timing." : "Observed fixture history with point controls and a complete table alternative."} stateType="OBS" data={metrics[0].series} unit={metrics[0].unit} publicationClass={snapshot.snapshot.publicationClass} /><aside className="sm-inspector sm-inspector--desktop" aria-label="Source inspector"><SourceInspectorContent sources={sources} factual={factual} /></aside><details className="sm-inspector sm-inspector--mobile"><summary>Source inspector <span>Evidence details</span></summary><SourceInspectorContent sources={sources} factual={factual} /></details></div><section className="sm-evidence-table" aria-labelledby="evidence-record-title"><div className="sm-section-heading"><div><span className="sm-eyebrow">Read-only records</span><h2 id="evidence-record-title">{factual ? "Factual OBS records" : "Typed fixture records"}</h2></div>{factual ? <FactualCandidateNotice compact /> : <FixtureNotice compact />}</div><div className="sm-table-scroll" role="region" aria-label={factual ? "Factual observation records" : "Typed fixture records"} tabIndex={0}><table><thead><tr><th>Record</th><th>State</th><th>Value</th><th>Valid time</th><th>Method / provenance</th></tr></thead><tbody>{metrics.map((metric) => <tr key={metric.id}><th scope="row">{metric.label}</th><td><DataStateLabel state={metric.stateType} /></td><td>{metric.displayValue}</td><td>{metric.validTime}</td><td>{metric.method ?? metric.provenanceRefs.join(", ")}</td></tr>)}</tbody></table></div></section><section className="sm-timing-strip"><h2>Timing boundaries</h2><dl><div><dt>System evaluated</dt><dd>{snapshot.snapshot.evaluatedAt}</dd></div><div><dt>{factual ? "Candidate generated" : "Snapshot generated"}</dt><dd>{snapshot.snapshot.generatedAt}</dd></div><div><dt>Public activation</dt><dd>{factual ? "Not activated" : snapshot.snapshot.publishedAt}</dd></div><div><dt>Operational knowledge cutoff</dt><dd>{snapshot.snapshot.asOf}</dd></div></dl></section></div>;
}
