import { ChartFrame } from "../../shared/ChartFrame";
import { DataStateLabel, FactualCandidateNotice, FixtureNotice, FreshnessLabel, SourceEvidenceLink } from "../../shared/Semantic";
import type { MetricRecord, ProvenanceRecord, RevisionReplayEvidence, SourceRecord } from "../../data/publicSnapshotTypes";
import { SystemIcon, type SystemIconName } from "../../shared/SystemIcon";
import type { ViewProps } from "../viewProps";

function SourceInspectorContent({ sources, provenance, factual }: { sources: SourceRecord[]; provenance: Record<string, ProvenanceRecord>; factual: boolean }) {
  return <><span className="sm-eyebrow">Source inspector</span><h2>Timing and provenance</h2>{sources.map((source) => {
    const records = Object.values(provenance).filter((record) => record.sourceId === source.sourceId);
    const seriesIds = [...new Set(records.flatMap((record) => record.seriesIds))];
    const evidenceLinks = records.flatMap((record) => record.seriesIds.map((seriesId) => ({ seriesId, href: record.seriesEvidenceUrls[seriesId] })));
    return <details className="sm-source-record" key={source.sourceId}><summary><strong>{source.provider}</strong><FreshnessLabel state={source.freshness} /></summary><dl><div><dt>Dataset</dt><dd>{source.dataset}</dd></div>{factual && <div><dt>Official series</dt><dd>{seriesIds.map((seriesId) => <code key={seriesId}>{seriesId}</code>)}</dd></div>}<div><dt>Observation</dt><dd>{source.observationTime}</dd></div><div><dt>Source publication</dt><dd>{source.publishedAt}</dd></div><div><dt>Retrieved</dt><dd>{source.retrievedAt}</dd></div><div><dt>Freshness evaluated</dt><dd>{source.freshnessEvaluatedAt}</dd></div><div><dt>Next expected release</dt><dd>{source.nextExpectedReleaseAt}</dd></div><div><dt>Revision / vintage</dt><dd>{source.revision} / {source.vintage}</dd></div><div><dt>Why this state</dt><dd>{source.freshnessReason}</dd></div></dl><div className="sm-evidence-links">{factual && evidenceLinks.map(({ seriesId, href }) => <span key={seriesId}><small>Source / data evidence</small><SourceEvidenceLink href={href}>Open {seriesId} data</SourceEvidenceLink></span>)}<span><small>Methodology</small><SourceEvidenceLink href={source.methodologyUrl}>{factual ? "Open official methodology" : "Open fixture methodology boundary"}</SourceEvidenceLink></span></div></details>;
  })}</>;
}

function FactualEvidenceCell({ metric, provenance }: { metric: MetricRecord; provenance: Record<string, ProvenanceRecord> }) {
  const record = metric.provenanceRefs.map((reference) => provenance[reference]).find(Boolean);
  const seriesId = metric.sourceSeriesIds?.[0];
  return <><code>{seriesId}</code>{record && seriesId && <SourceEvidenceLink href={record.seriesEvidenceUrls[seriesId]}>Open original evidence</SourceEvidenceLink>}</>;
}

function DolRevisionProof({ proof }: { proof?: RevisionReplayEvidence }) {
  if (!proof) return null;
  return <section className="sm-revision-proof" aria-label="DOL revision and replay evidence"><details><summary><span><strong>DOL revision and replay example</strong><small>{proof.label}</small></span><b>217,000 → 210,000</b></summary><div className="sm-revision-grid">{proof.releases.map((release) => <article key={release.releaseId}><span>{release.label}</span><strong>{release.displayValue}</strong><time dateTime={release.publishedAt}>{release.publishedAt}</time><SourceEvidenceLink href={release.evidenceUrl}>Open original DOL release</SourceEvidenceLink></article>)}</div><dl><div><dt>As known March 10</dt><dd>{proof.asKnown.displayValue}</dd></div><div><dt>Latest revised truth</dt><dd>{proof.latestRevisedTruth.displayValue}</dd></div></dl><p>The same week-ending observation is replayed by its public-knowledge cutoff without overwriting the later revised truth.</p></details></section>;
}

function Phase4bEvidence({ phase4b }: { phase4b: NonNullable<ViewProps["phase4b"]> }) {
  return <section className="sm-evidence-table sm-phase4b-evidence" aria-labelledby="phase4b-evidence-title"><div className="sm-section-heading"><div><span className="sm-eyebrow">Phase-4B source boundary</span><h2 id="phase4b-evidence-title">Current energy and transport OBS</h2></div><span className="sm-gate-badge">0 structural CALC</span></div><div className="sm-table-scroll" role="region" aria-label="Phase-4B factual observation evidence" tabIndex={0}><table><thead><tr><th>Record</th><th>Identity</th><th>Value</th><th>Period</th><th>Publisher / series</th><th>Evidence</th></tr></thead><tbody>{phase4b.observations.map((observation) => <tr key={observation.id}><th scope="row">{observation.label}</th><td><DataStateLabel state="OBS" /></td><td>{observation.value} {observation.unit.replaceAll("_", " ")}</td><td>{observation.period}</td><td>{observation.authority}<br /><code>{observation.seriesId}</code></td><td className="sm-series-evidence"><SourceEvidenceLink href={observation.evidenceUrl}>Open original evidence</SourceEvidenceLink><details><summary>More provenance</summary><a href={observation.methodologyUrl} target="_blank" rel="noreferrer">Methodology</a><a href={observation.acquisitionProvenanceUrl} target="_blank" rel="noreferrer">Machine acquisition</a></details></td></tr>)}</tbody></table></div><p className="sm-evidence-note">These are official observations. No Phase-4B structural calculation or accepted structural relationship exists in this local candidate.</p></section>;
}

export default function VerifiedDataView({ snapshot, phase4b, route, navigate }: ViewProps) {
  const metrics = snapshot.extensions["auxsays.phase2.metrics"];
  const sources = Object.values(snapshot.sources);
  const provenance = snapshot.extensions["auxsays.phase3.provenance"] ?? {};
  const revisionProof = snapshot.extensions["auxsays.phase3.revisionEvidence"]?.[0];
  const geographies = snapshot.extensions["auxsays.phase2.geographies"];
  const ranges = snapshot.extensions["auxsays.phase2.ranges"];
  const factual = snapshot.snapshot.publicationClass === "factual";
  if (factual && phase4b) {
    const icons: SystemIconName[] = ["barrel", "gauge", "truck"];
    return <div className="sm-view sm-view--verified sm-view--evidence-experience">
      <header className="sm-evidence-hero"><span className="sm-kicker"><i aria-hidden="true" />Evidence room</span><h1 data-route-heading tabIndex={-1}>Trust the number.<br /><em>Trace the source.</em></h1><p>The proof stays quiet until you ask for it.</p></header>
      <section className="sm-evidence-stack" aria-labelledby="evidence-stack-title"><div className="sm-section-intro"><div><span>01</span><div><small>Current layer</small><h2 id="evidence-stack-title">Official measurements</h2></div></div><span className="sm-evidence-count">{phase4b.observations.length} records</span></div>{phase4b.observations.map((observation, index) => <details className="sm-evidence-card" key={observation.id}><summary><span className="sm-evidence-card__icon"><SystemIcon name={icons[index] ?? "database"} size={26} /></span><span><strong>{observation.label}</strong><small>{observation.authority}</small></span><b>{observation.value}{observation.unit === "percent" ? "%" : ""}</b><i aria-hidden="true">+</i></summary><div className="sm-evidence-card__body"><div className="sm-evidence-facts"><div><span>Period</span><strong>{observation.period}</strong></div><div><span>Series</span><strong>{observation.seriesId}</strong></div><div><span>Identity</span><strong>Official measurement</strong></div><div><span>AUXSAYS calculation</span><strong>None</strong></div></div><div className="sm-evidence-actions"><SourceEvidenceLink href={observation.evidenceUrl}>Open original evidence <SystemIcon name="arrow" size={16} /></SourceEvidenceLink><a href={observation.methodologyUrl} target="_blank" rel="noreferrer">Methodology</a><a href={observation.acquisitionProvenanceUrl} target="_blank" rel="noreferrer">Machine acquisition record</a></div></div></details>)}</section>
      <details className="sm-evidence-archive"><summary><span><SystemIcon name="database" size={22} /><span><strong>Gate A labor evidence</strong><small>Six earlier factual records and the DOL revision proof</small></span></span><i aria-hidden="true">+</i></summary><div><div className="sm-table-scroll" role="region" aria-label="Factual observation records" tabIndex={0}><table><thead><tr><th>Record</th><th>Value</th><th>Period</th><th>Series / evidence</th></tr></thead><tbody>{metrics.map((metric) => <tr key={metric.id}><th scope="row">{metric.label}</th><td>{metric.displayValue}</td><td>{metric.validTime}</td><td className="sm-series-evidence"><FactualEvidenceCell metric={metric} provenance={provenance} /></td></tr>)}</tbody></table></div><DolRevisionProof proof={revisionProof} /></div></details>
      <details className="sm-technical-drawer sm-technical-drawer--evidence"><summary>Source health and acquisition state <span>Inspect system layer</span></summary><div><dl>{Object.entries(phase4b.sourceHealth).map(([source, status]) => <div key={source}><dt>{source}</dt><dd>{status}</dd></div>)}</dl></div></details>
    </div>;
  }
  return <div className="sm-view sm-view--verified">
    <header className="sm-view-header"><div><span className="sm-eyebrow">Verified Data / Evidence</span><h1 data-route-heading tabIndex={-1}>{factual ? "Observed factual evidence — local review candidate" : "Observed and calculated fixture evidence"}</h1></div><div className="sm-control-pair"><label>Geography<select value={route.geo} onChange={(event) => navigate((current) => ({ ...current, geo: event.target.value }))}>{geographies.map((geo) => <option key={geo.id} value={geo.id}>{geo.label}</option>)}</select></label><label>Range<select value={route.range} onChange={(event) => navigate((current) => ({ ...current, range: event.target.value }))}>{ranges.map((range) => <option key={range.id} value={range.id}>{range.label}</option>)}</select></label></div></header>
    {factual && phase4b && <Phase4bEvidence phase4b={phase4b} />}
    <div className="sm-primary-layout"><ChartFrame title={factual ? metrics[0].label : "Verified fixture history"} description={factual ? "Latest factual observation with separate valid, public, retrieved, and accepted timing." : "Observed fixture history with point controls and a complete table alternative."} stateType="OBS" data={metrics[0].series} unit={metrics[0].unit} publicationClass={snapshot.snapshot.publicationClass} /><aside className="sm-inspector sm-inspector--desktop" aria-label="Source inspector"><SourceInspectorContent sources={sources} provenance={provenance} factual={factual} /></aside><details className="sm-inspector sm-inspector--mobile"><summary>Source inspector <span>Evidence details</span></summary><SourceInspectorContent sources={sources} provenance={provenance} factual={factual} /></details></div>
    <section className="sm-evidence-table" aria-labelledby="evidence-record-title"><div className="sm-section-heading"><div><span className="sm-eyebrow">Read-only records</span><h2 id="evidence-record-title">{factual ? "Factual OBS records" : "Typed fixture records"}</h2></div>{factual ? <FactualCandidateNotice compact active={Boolean(snapshot.snapshot.publishedAt)} /> : <FixtureNotice compact />}</div><div className="sm-table-scroll" role="region" aria-label={factual ? "Factual observation records" : "Typed fixture records"} tabIndex={0}><table><thead><tr><th>Record</th><th>State</th><th>Value</th><th>Valid time</th>{factual ? <><th>Source</th><th>Series / evidence</th></> : <th>Method / provenance</th>}</tr></thead><tbody>{metrics.map((metric) => <tr key={metric.id}><th scope="row">{metric.label}</th><td><DataStateLabel state={metric.stateType} /></td><td>{metric.displayValue}</td><td>{metric.validTime}</td>{factual ? <><td>{snapshot.sources[metric.sourceRefs[0]]?.provider}</td><td className="sm-series-evidence"><FactualEvidenceCell metric={metric} provenance={provenance} /></td></> : <td>{metric.method ?? metric.provenanceRefs.join(", ")}</td>}</tr>)}</tbody></table></div></section>
    {factual && <DolRevisionProof proof={revisionProof} />}
    <section className="sm-timing-strip"><h2>Timing boundaries</h2><dl><div><dt>System evaluated</dt><dd>{snapshot.snapshot.evaluatedAt}</dd></div><div><dt>{factual ? "Candidate generated" : "Snapshot generated"}</dt><dd>{snapshot.snapshot.generatedAt}</dd></div><div><dt>Public activation</dt><dd>{factual ? "Not activated" : snapshot.snapshot.publishedAt}</dd></div><div><dt>Operational knowledge cutoff</dt><dd>{snapshot.snapshot.asOf}</dd></div></dl></section>
  </div>;
}
