#!/usr/bin/env python3
"""The official-ingestion source-health band must account for every source it lists.

The band on /updates/methodology/ sums `site.data.source_health` into one tile per status. That
only tells the truth while the tile names and the writer's vocabulary agree, and NOTHING in Jekyll
enforced that agreement -- a `where` filter on a status the data no longer uses silently returns
zero, so the tiles could report "no failing sources" over a table that lists several.

The drift is not hypothetical. `scripts/source_health_snapshot.py` originally emitted
Healthy / Idle healthy / Degraded / Failing / Staged / Enabled / Manual watch / Disabled; commit
4406ebee migrated it to Error / Unknown / Active / Manual watch / Needs adapter / Disabled and
hand-edited the page tiles to match in the same commit. The tracked `_data/source_health.yml` was
deliberately left behind (it is regenerated during the Pages build), and against THAT file the band
renders five zeros and drops 23 of its 37 sources out of every tile.

So the band no longer relies on the two sides agreeing. It counts the remainder into an "Other"
tile and states the total it covers, making it self-accounting under any data. This locks:

  - sum of the rendered tiles == number of rendered rows, for the tracked snapshot, for a snapshot
    freshly generated by the shipped writer, for off-vocabulary data, and for no data at all;
  - the stated total is the real rendered row count;
  - the page's six named tiles are exactly PUBLIC_SOURCE_STATUSES, and status_for cannot return
    anything else;
  - the per-SOURCE vocabulary stays separate from the per-patch collector vocabulary in
    evidence_method_health.yml -- "Disabled" means a different thing in each.

Where Ruby + the liquid gem are available the render assertions run against a REAL Liquid render of
the verbatim shipped template block; otherwise those cases SKIP and the structural assertions still
run. Jekyll itself cannot be loaded here (eventmachine is missing), so its `where` filter is
mirrored in the render harness -- see jekyll_where_note().

Run: PYTHONDONTWRITEBYTECODE=1 python auxsays/scripts/tests/test_public_source_health_presentation.py
"""
from __future__ import annotations

import ast
import json
import re
import shutil
import subprocess
import sys
import tempfile
import traceback
from pathlib import Path

import yaml

_REPO = Path(__file__).resolve().parents[3]
_AUX = _REPO / "auxsays"

PAGE_PATH = _AUX / "updates" / "methodology" / "index.md"
CSS_PATH = _AUX / "assets" / "css" / "auxsays-custom.css"
WRITER_PATH = _AUX / "scripts" / "source_health_snapshot.py"
DATA_PATH = _AUX / "_data" / "source_health.yml"

PAGE = PAGE_PATH.read_text(encoding="utf-8")
CSS = CSS_PATH.read_text(encoding="utf-8")

# The per-PATCH collector taxonomy. Keyed on the identity triple plus method_id, stored in
# _data/evidence_method_health.yml, rendered by its own band higher up the same page. It is a
# different thing from per-source adapter health and must never be counted into these tiles.
METHOD_HEALTH_STATUSES = {
    "success", "partial", "no_results", "blocked", "stale", "broken",
    "low_confidence", "disabled", "manual_review_needed",
}

_PASS = 0
_FAIL = 0
_SKIP = 0
_ERRORS: list[str] = []


def check(label: str, condition: bool, detail: str = "") -> None:
    global _PASS, _FAIL
    if condition:
        _PASS += 1
        print(f"  PASS  {label}")
    else:
        _FAIL += 1
        _ERRORS.append(label)
        print(f"  FAIL  {label}" + (f"\n        {detail}" if detail else ""))


def skip(label: str, why: str) -> None:
    global _SKIP
    _SKIP += 1
    print(f"  SKIP  {label}\n        {why}")


# ---------------------------------------------------------------- template slicing


def source_health_block(page_text: str) -> str:
    """The verbatim shipped source-health section body: the tile band plus the row table.

    Anchored on the section element and its first `{% assign %}`, not on any particular assign.
    An anchor naming a variable this change introduced would make the suite unrunnable against a
    pre-change page instead of failing it on the arithmetic, which is the whole point."""
    section = page_text.index('class="panel methodology-source-health')
    start = page_text.index("{% assign", section)
    return page_text[start:page_text.index("</section>", start)]


def summary_only(block: str) -> str:
    """Just the tile band -- the assigns, the tiles and the total, without the row table."""
    return block[:block.index('<div class="source-health-table"')]


def without_other_bucket(block: str) -> str:
    """The block with the Other tile and the total removed -- a synthetic PRE-FIX template.

    Deriving the pre-fix template from the current one (rather than reading it out of git) keeps
    the non-vacuity proof true after this change merges, when `main` IS the fixed template."""
    stripped = re.sub(r"\{%\s*if other_sources > 0 %\}.*?\{%\s*endif\s*%\}\n?", "", block, flags=re.S)
    return re.sub(r"\{%\s*if source_health_total > 0 %\}.*?\{%\s*endif\s*%\}\n?", "", stripped, flags=re.S)


# ---------------------------------------------------------------- real Liquid render


def jekyll_where_note() -> str:
    """Why the harness defines `where` itself.

    `where` ships with Jekyll, not with the liquid gem, and the band depends on it. Jekyll cannot
    be required in this environment, so the harness registers the jekyll-4.4.1 Jekyll::Filters#where
    behaviour for the only shape this band uses: an array of hashes selected on a scalar property
    compared as strings."""
    return "mirrors jekyll-4.4.1 Jekyll::Filters#where for array-of-hash / scalar property"


_RENDER_SCRIPT = """
require 'liquid'
require 'json'

# `where` ships with Jekyll, not with the liquid gem. See jekyll_where_note().
module JekyllWhereFilter
  def where(input, property, value)
    return input if !input.is_a?(Enumerable) || property.nil? || value.nil?
    input = input.values if input.is_a?(Hash)
    input.select { |object| object.is_a?(Hash) && object[property].to_s == value.to_s }
  end
end
Liquid::Template.register_filter(JekyllWhereFilter)

payload = JSON.parse(File.read(ARGV[0]))
tpl = Liquid::Template.parse(payload['template'])
# render! (not render): a Liquid error must RAISE, not be embedded in the output as text where an
# assertion could read straight past it.
print tpl.render!(payload['vars'])
"""


def liquid_render(template: str, variables: dict) -> str | None:
    """Render `template` with the real liquid gem. None if Ruby/liquid is unavailable."""
    ruby = shutil.which("ruby")
    if not ruby:
        return None
    with tempfile.TemporaryDirectory() as td:
        script = Path(td) / "render.rb"
        script.write_text(_RENDER_SCRIPT, encoding="utf-8")
        payload = Path(td) / "payload.json"
        payload.write_text(json.dumps({"template": template, "vars": variables}), encoding="utf-8")
        proc = subprocess.run([ruby, str(script), str(payload)],
                              capture_output=True, text=True, timeout=120)
        if proc.returncode != 0:
            return None
        return proc.stdout


def render_band(rows, *, template: str | None = None) -> str | None:
    block = template if template is not None else source_health_block(PAGE)
    return liquid_render(block, {"site": {"data": {"source_health": rows}}})


def tiles_of(out: str) -> list[tuple[int, str]]:
    """(count, label) for every tile the band actually rendered, in render order."""
    return [(int(n), label) for n, label in
            re.findall(r"<div><strong>(\d+)</strong><span>([^<]*)</span></div>", out)]


def rendered_rows(out: str) -> int:
    """Data rows in the table. Counted on the per-source id cell, which the head row has not."""
    return out.count('<span class="source-health-id">')


def stated_total(out: str) -> int | None:
    found = re.search(r'<p class="source-health-total">[^<]*?all (\d+) tracked source', out)
    return int(found.group(1)) if found else None


def source_row(status: str, source_id: str = "probe") -> dict:
    """One source-health row shaped as source_health_snapshot.py writes it."""
    return {
        "source_id": source_id, "company_id": "probe-co", "product_id": source_id,
        "company": "Probe", "software": "Probe App", "public_category": "creator",
        "adapter_type": "probe_adapter", "enabled": True, "status": status,
        "status_detail": status, "polling_frequency": "6h", "last_success": "",
        "last_error": "", "last_error_display": "None", "last_error_type": "",
        "consecutive_failures": 0, "last_checked": "", "last_records_fetched": 0,
        "last_records_written": 0, "last_records_skipped": 0, "last_run_duration_ms": 0,
        "last_health_note": "", "capabilities": {}, "raw_extractable_fields": {},
    }


def _writer_module():
    sys.path.insert(0, str(_AUX / "scripts"))
    import source_health_snapshot as snapshot  # noqa: PLC0415
    return snapshot


def build_time_snapshot() -> list[dict]:
    """What the Pages build actually renders: the shipped writer run on the shipped inputs.

    CONFIG_PATH and STATE_PATH are bound at import from the real repo, so redirecting ROOT and
    OUTPUT_PATH afterwards changes only where the snapshot is written (and the path main() prints
    it relative to). The repo's own _data/source_health.yml is never touched."""
    snapshot = _writer_module()
    with tempfile.TemporaryDirectory() as td:
        out = Path(td) / "source_health.yml"
        root, output = snapshot.ROOT, snapshot.OUTPUT_PATH
        snapshot.ROOT, snapshot.OUTPUT_PATH = Path(td), out
        try:
            snapshot.main()
        finally:
            snapshot.ROOT, snapshot.OUTPUT_PATH = root, output
        return yaml.safe_load(out.read_text(encoding="utf-8")) or []


# ---------------------------------------------------------------- the suite


def run() -> int:
    print("=" * 74)
    print("Public source-health band -- the tiles must account for every listed source")
    print("=" * 74)

    liquid_ok = liquid_render("{{ x }}", {"x": "ok"}) == "ok"
    if not liquid_ok:
        print("\n  (Ruby + liquid gem unavailable: render cases will SKIP, structure still checked)")

    block = source_health_block(PAGE)
    summary = summary_only(block)
    vocabulary = _writer_module().PUBLIC_SOURCE_STATUSES

    # ---------- S1: the tracked snapshot ----------
    print("\n[S1] the tracked _data/source_health.yml is fully accounted for")
    tracked = yaml.safe_load(DATA_PATH.read_text(encoding="utf-8")) or []
    if not liquid_ok:
        skip("S1 (render)", "no Ruby/liquid")
    else:
        out = render_band(tracked)
        tiles = tiles_of(out)
        check("S1 every tracked source lands in exactly one tile",
              sum(n for n, _ in tiles) == rendered_rows(out) == len(tracked),
              f"tiles={tiles} rendered_rows={rendered_rows(out)} data_rows={len(tracked)}")
        check("S1 the stated total is the real rendered row count",
              stated_total(out) == rendered_rows(out),
              f"stated={stated_total(out)} rendered={rendered_rows(out)}")

    # ---------- S2: what the Pages build actually renders ----------
    print("\n[S2] the snapshot the build generates needs no Other bucket at all")
    fresh = build_time_snapshot()
    unnamed = {row.get("status") for row in fresh} - set(vocabulary)
    check("S2 the writer emits only its declared vocabulary", fresh and not unnamed, str(sorted(unnamed)))
    if not liquid_ok:
        skip("S2 (render)", "no Ruby/liquid")
    else:
        out = render_band(fresh)
        tiles = tiles_of(out)
        check("S2 the named tiles alone cover the whole build-time snapshot",
              sum(n for n, _ in tiles) == rendered_rows(out) == len(fresh),
              f"tiles={tiles} rendered_rows={rendered_rows(out)} data_rows={len(fresh)}")
        check("S2 no Other tile is rendered when nothing falls outside the vocabulary",
              "Other" not in [label for _, label in tiles], str(tiles))

    # ---------- S3: a vocabulary the page does not name ----------
    print("\n[S3] off-vocabulary statuses are counted, never dropped")
    # The writer's own pre-4406ebee names: exactly what a stale or rolled-back snapshot holds.
    legacy = [source_row(s, f"legacy-{i}") for i, s in
              enumerate(("Healthy", "Staged", "Failing", "Degraded", "Idle healthy", "Enabled"))]
    mixed = legacy + [source_row("Active", "current-1"), source_row("Error", "current-2")]
    if not liquid_ok:
        skip("S3 (render)", "no Ruby/liquid")
    else:
        out = render_band(mixed)
        tiles = {label: n for n, label in tiles_of(out)}
        check("S3 the tiles still sum to the rendered rows",
              sum(tiles.values()) == rendered_rows(out) == len(mixed),
              f"tiles={tiles} rendered_rows={rendered_rows(out)}")
        check("S3 every unnamed status is counted under Other",
              tiles.get("Other") == len(legacy), str(tiles))
        check("S3 the named statuses are still counted by name",
              tiles.get("Active") == 1 and tiles.get("Error") == 1, str(tiles))
        check("S3 the stated total covers them too",
              stated_total(out) == len(mixed), str(stated_total(out)))

        # Non-vacuity: without the Other tile the same data under-reports. If this ever passes,
        # the guarantee has been removed and S3 above has become a tautology.
        pre_fix = render_band(mixed, template=without_other_bucket(block))
        check("S3 non-vacuity: the pre-fix band really did drop those sources",
              pre_fix is not None
              and sum(n for n, _ in tiles_of(pre_fix)) == len(mixed) - len(legacy)
              and rendered_rows(pre_fix) == len(mixed),
              str(tiles_of(pre_fix) if pre_fix else None))

    # ---------- S4: no data ----------
    print("\n[S4] an absent snapshot renders honestly rather than failing")
    if not liquid_ok:
        skip("S4 (render)", "no Ruby/liquid")
    else:
        for label, data in (("an empty list", []), ("no data file at all", None)):
            out = render_band(data)
            check(f"S4 {label}: renders, zero tiles, zero rows",
                  out is not None and sum(n for n, _ in tiles_of(out)) == 0 == rendered_rows(out),
                  str(tiles_of(out)) if out else "render failed")
            check(f"S4 {label}: claims no total it cannot back",
                  out is not None and stated_total(out) is None,
                  str(out)[:200] if out else "render failed")

    # ---------- S5: page and writer name the same six statuses ----------
    print("\n[S5] the tile names and the writer's vocabulary are one contract")
    filtered = re.findall(r'where:\s*"status",\s*"([^"]+)"', summary)
    check("S5 the band filters on exactly PUBLIC_SOURCE_STATUSES",
          set(filtered) == set(vocabulary) and len(filtered) == len(set(filtered)),
          f"page={sorted(filtered)} writer={sorted(vocabulary)}")
    labels = re.findall(r"<div><strong>\{\{ \w+\.size \}\}</strong><span>([^<]+)</span></div>", summary)
    check("S5 one tile per status, labelled with the status it counts",
          set(labels) == set(vocabulary), f"labels={sorted(labels)}")
    order = {status: index for index, status in enumerate(vocabulary)}
    check("S5 the snapshot's audit sort covers the vocabulary and nothing else",
          set(order) == set(vocabulary))

    # ---------- S6: status_for cannot invent a status ----------
    print("\n[S6] status_for can only return statuses the band names")
    tree = ast.parse(WRITER_PATH.read_text(encoding="utf-8"))
    fn = next(n for n in ast.walk(tree)
              if isinstance(n, ast.FunctionDef) and n.name == "status_for")
    returns = [n for n in ast.walk(fn) if isinstance(n, ast.Return)]
    literals: set[str] = set()
    opaque: list[str] = []
    for node in returns:
        first = node.value.elts[0] if isinstance(node.value, ast.Tuple) and node.value.elts else None
        if isinstance(first, ast.Constant) and isinstance(first.value, str):
            literals.add(first.value)
        else:
            opaque.append(ast.unparse(node))
    check("S6 every return is a literal status the test can actually read",
          bool(returns) and not opaque, str(opaque))
    check("S6 every status it can return has a tile",
          bool(literals) and literals <= set(vocabulary),
          f"unnamed={sorted(literals - set(vocabulary))}")

    # ---------- S7: the two health taxonomies stay apart ----------
    print("\n[S7] per-source health is not the per-patch collector taxonomy")
    check("S7 the band reads only the source-health data file",
          "site.data.source_health" in summary and "evidence_method_health" not in summary)
    check("S7 no collector status has leaked into the source tiles",
          not (set(filtered) & METHOD_HEALTH_STATUSES),
          str(sorted(set(filtered) & METHOD_HEALTH_STATUSES)))
    # The collector band is a separate section with its own vocabulary; it must still be there.
    check("S7 the collector band still counts its own statuses separately",
          'where: "status", "manual_review_needed"' in PAGE and 'where: "status", "blocked"' in PAGE)

    # ---------- S8: the guard idiom ----------
    print("\n[S8] the band uses no always-true `blank` guard")
    # Liquid resolves the `blank` literal as MethodLiteral(:blank?) and no String#blank? exists
    # outside Rails, so `x != blank` is nil-inverted to ALWAYS TRUE -- a guard that never guards.
    check("S8 nothing in the band compares against `blank`",
          not re.search(r"[!=]=\s*blank\b", summary), summary)

    # ---------- S9: the status pill states the status in colour ----------
    print("\n[S9] every current status has a pill style, not just the retired ones")
    missing = [s for s in vocabulary
               if f".source-health-status--{s.lower().replace(' ', '-')}" not in CSS]
    check("S9 the CSS covers the vocabulary the writer emits today", not missing, str(missing))
    check("S9 the total caption has a style of its own", ".source-health-total {" in CSS)

    print()
    print("=" * 74)
    print(f"Results: {_PASS}/{_PASS + _FAIL} passed, {_FAIL} failed"
          + (f", {_SKIP} skipped" if _SKIP else ""))
    if _ERRORS:
        for e in _ERRORS:
            print(f"  - {e}")
    print("=" * 74)
    return 1 if _FAIL else 0


if __name__ == "__main__":
    try:
        raise SystemExit(run())
    except SystemExit:
        raise
    except Exception:
        traceback.print_exc()
        raise SystemExit(1)
